
apiVersion: v1
kind: Pod
metadata:
  name: simple-node
spec:
  containers:
    - image: YOUR-CONTAINER-REGISTRY/simple-node:latest
      name: simple-node
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
